CREATE DATABASE IF NOT EXISTS db_gestion_alumnos;
USE db_gestion_alumnos;

CREATE TABLE IF NOT EXISTS carreras(
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL UNIQUE,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS alumnos(
id INT NOT NULL AUTO_INCREMENT,
apellido_nombre VARCHAR(30) NOT NULL,
dni INT(8) UNSIGNED NOT NULL UNIQUE,
email VARCHAR(30),
telefono VARCHAR(15),
carrera_id INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (carrera_id) REFERENCES carreras (id)
	ON DELETE NO ACTION
    ON UPDATE CASCADE
);